// Define the Country model
class CountryAPI {
  final int id;
  final String name;
  final int phoneCode;

  CountryAPI({
    required this.id,
    required this.name,
    required this.phoneCode,
  });
}

List<CountryAPI> countriesAPI = [
  CountryAPI(id: 1, name: "Egypt", phoneCode: 20),
  CountryAPI(id: 3, name: "Afghanistan", phoneCode: 93),
  CountryAPI(id: 4, name: "United Arab Emirates", phoneCode: 971),
  CountryAPI(id: 5, name: "Saudi Arabia", phoneCode: 966),
  CountryAPI(id: 6, name: "Kuwait", phoneCode: 956),
  CountryAPI(id: 7, name: "Qater", phoneCode: 974),
  CountryAPI(id: 8, name: "Antigua and Barbuda", phoneCode: 1),
  CountryAPI(id: 9, name: "Argentina", phoneCode: 54),
  CountryAPI(id: 10, name: "Armenia", phoneCode: 374),
  CountryAPI(id: 11, name: "Australia", phoneCode: 61),
  CountryAPI(id: 12, name: "Austria", phoneCode: 43),
  CountryAPI(id: 13, name: "Azerbaijan", phoneCode: 994),
  CountryAPI(id: 14, name: "Bahamas", phoneCode: 1),
  CountryAPI(id: 15, name: "Bahrain", phoneCode: 973),
  CountryAPI(id: 16, name: "Bangladesh", phoneCode: 880),
  CountryAPI(id: 17, name: "Barbados", phoneCode: 1),
  CountryAPI(id: 18, name: "Belarus", phoneCode: 375),
  CountryAPI(id: 19, name: "Belgium", phoneCode: 32),
  CountryAPI(id: 20, name: "Belize", phoneCode: 501),
  CountryAPI(id: 21, name: "Benin", phoneCode: 229),
  CountryAPI(id: 22, name: "Bhutan", phoneCode: 975),
  CountryAPI(id: 23, name: "Bolivia", phoneCode: 591),
  CountryAPI(id: 24, name: "Bosnia and Herzegovina", phoneCode: 387),
  CountryAPI(id: 25, name: "Botswana", phoneCode: 267),
  CountryAPI(id: 26, name: "Brazil", phoneCode: 55),
  CountryAPI(id: 27, name: "Brunei", phoneCode: 673),
  CountryAPI(id: 28, name: "Bulgaria", phoneCode: 359),
  CountryAPI(id: 29, name: "Burkina Faso", phoneCode: 226),
  CountryAPI(id: 30, name: "Burundi", phoneCode: 257),
  CountryAPI(id: 31, name: "Cabo Verde", phoneCode: 238),
  CountryAPI(id: 32, name: "Cambodia", phoneCode: 855),
  CountryAPI(id: 33, name: "Cameroon", phoneCode: 237),
  CountryAPI(id: 34, name: "Canada", phoneCode: 1),
  CountryAPI(id: 35, name: "Central African Republic", phoneCode: 236),
  CountryAPI(id: 36, name: "Chad", phoneCode: 235),
  CountryAPI(id: 37, name: "Chile", phoneCode: 56),
  CountryAPI(id: 38, name: "China", phoneCode: 86),
  CountryAPI(id: 39, name: "Colombia", phoneCode: 57),
  CountryAPI(id: 40, name: "Comoros", phoneCode: 269),
  CountryAPI(id: 41, name: "Congo", phoneCode: 242),
  CountryAPI(id: 42, name: "Costa Rica", phoneCode: 506),
  CountryAPI(id: 43, name: "Croatia", phoneCode: 385),
  CountryAPI(id: 44, name: "Cuba", phoneCode: 53),
  CountryAPI(id: 45, name: "Cyprus", phoneCode: 357),
  CountryAPI(id: 46, name: "Czech Republic", phoneCode: 420),
  CountryAPI(id: 47, name: "Denmark", phoneCode: 45),
  CountryAPI(id: 48, name: "Djibouti", phoneCode: 253),
  CountryAPI(id: 49, name: "Dominica", phoneCode: 1),
  CountryAPI(id: 50, name: "Dominican Republic", phoneCode: 1),
  CountryAPI(id: 51, name: "Ecuador", phoneCode: 593),
  CountryAPI(id: 53, name: "El Salvador", phoneCode: 503),
  CountryAPI(id: 54, name: "Equatorial Guinea", phoneCode: 240),
  CountryAPI(id: 55, name: "Eritrea", phoneCode: 291),
  CountryAPI(id: 56, name: "Estonia", phoneCode: 372),
  CountryAPI(id: 57, name: "Eswatini", phoneCode: 268),
  CountryAPI(id: 58, name: "Ethiopia", phoneCode: 251),
  CountryAPI(id: 59, name: "Fiji", phoneCode: 679),
  CountryAPI(id: 60, name: "Finland", phoneCode: 358),
  CountryAPI(id: 61, name: "France", phoneCode: 33),
  CountryAPI(id: 62, name: "Gabon", phoneCode: 241),
  CountryAPI(id: 63, name: "Gambia", phoneCode: 220),
  CountryAPI(id: 64, name: "Georgia", phoneCode: 995),
  CountryAPI(id: 65, name: "Germany", phoneCode: 49),
  CountryAPI(id: 66, name: "Ghana", phoneCode: 233),
  CountryAPI(id: 67, name: "Greece", phoneCode: 30),
  CountryAPI(id: 68, name: "Grenada", phoneCode: 1),
  CountryAPI(id: 69, name: "Guatemala", phoneCode: 502),
  CountryAPI(id: 70, name: "Guinea", phoneCode: 224),
  CountryAPI(id: 71, name: "Guinea-Bissau", phoneCode: 245),
  CountryAPI(id: 72, name: "Guyana", phoneCode: 592),
  CountryAPI(id: 73, name: "Haiti", phoneCode: 509),
  CountryAPI(id: 74, name: "Honduras", phoneCode: 504),
  CountryAPI(id: 75, name: "Hungary", phoneCode: 36),
  CountryAPI(id: 76, name: "Iceland", phoneCode: 354),
  CountryAPI(id: 77, name: "India", phoneCode: 91),
  CountryAPI(id: 78, name: "Indonesia", phoneCode: 62),
  CountryAPI(id: 79, name: "Iran", phoneCode: 98),
  CountryAPI(id: 80, name: "Iraq", phoneCode: 964),
  CountryAPI(id: 81, name: "Ireland", phoneCode: 353),
  CountryAPI(id: 82, name: "Israel", phoneCode: 972),
  CountryAPI(id: 83, name: "Italy", phoneCode: 39),
  CountryAPI(id: 84, name: "Jamaica", phoneCode: 1),
  CountryAPI(id: 85, name: "Japan", phoneCode: 81),
  CountryAPI(id: 86, name: "Jordan", phoneCode: 962),
  CountryAPI(id: 87, name: "Kazakhstan", phoneCode: 7),
  CountryAPI(id: 88, name: "Kenya", phoneCode: 254),
  CountryAPI(id: 89, name: "Kiribati", phoneCode: 686),
  CountryAPI(id: 90, name: "Korea, North", phoneCode: 850),
  CountryAPI(id: 91, name: "Korea, South", phoneCode: 82),
  CountryAPI(id: 92, name: "Andorra", phoneCode: 376),
  CountryAPI(id: 93, name: "Kyrgyzstan", phoneCode: 996),
  CountryAPI(id: 94, name: "Laos", phoneCode: 856),
  CountryAPI(id: 95, name: "Latvia", phoneCode: 371),
  CountryAPI(id: 96, name: "Lebanon", phoneCode: 961),
  CountryAPI(id: 97, name: "Lesotho", phoneCode: 266),
  CountryAPI(id: 98, name: "Liberia", phoneCode: 231),
  CountryAPI(id: 99, name: "Libya", phoneCode: 218),
  CountryAPI(id: 100, name: "Liechtenstein", phoneCode: 423),
  CountryAPI(id: 101, name: "Lithuania", phoneCode: 370),
  CountryAPI(id: 102, name: "Luxembourg", phoneCode: 352),
  CountryAPI(id: 103, name: "Madagascar", phoneCode: 261),
  CountryAPI(id: 104, name: "Malawi", phoneCode: 265),
  CountryAPI(id: 105, name: "Malaysia", phoneCode: 60),
  CountryAPI(id: 106, name: "Maldives", phoneCode: 960),
  CountryAPI(id: 107, name: "Mali", phoneCode: 223),
  CountryAPI(id: 108, name: "Malta", phoneCode: 356),
  CountryAPI(id: 109, name: "Marshall Islands", phoneCode: 692),
  CountryAPI(id: 110, name: "Mauritania", phoneCode: 222),
  CountryAPI(id: 111, name: "Mauritius", phoneCode: 230),
  CountryAPI(id: 112, name: "Mexico", phoneCode: 52),
  CountryAPI(id: 113, name: "Micronesia", phoneCode: 691),
  CountryAPI(id: 114, name: "Moldova", phoneCode: 373),
  CountryAPI(id: 115, name: "Monaco", phoneCode: 377),
  CountryAPI(id: 116, name: "Mongolia", phoneCode: 976),
  CountryAPI(id: 117, name: "Montenegro", phoneCode: 382),
  CountryAPI(id: 118, name: "Morocco", phoneCode: 212),
  CountryAPI(id: 119, name: "Mozambique", phoneCode: 258),
  CountryAPI(id: 120, name: "Myanmar", phoneCode: 95),
  CountryAPI(id: 121, name: "Namibia", phoneCode: 264),
  CountryAPI(id: 122, name: "Nauru", phoneCode: 674),
  CountryAPI(id: 123, name: "Nepal", phoneCode: 977),
  CountryAPI(id: 124, name: "Netherlands", phoneCode: 31),
  CountryAPI(id: 125, name: "New Zealand", phoneCode: 64),
  CountryAPI(id: 126, name: "Nicaragua", phoneCode: 505),
  CountryAPI(id: 127, name: "Niger", phoneCode: 227),
  CountryAPI(id: 128, name: "Nigeria", phoneCode: 234),
  CountryAPI(id: 129, name: "North Macedonia", phoneCode: 389),
  CountryAPI(id: 130, name: "Norway", phoneCode: 47),
  CountryAPI(id: 131, name: "Oman", phoneCode: 968),
  CountryAPI(id: 132, name: "Pakistan", phoneCode: 92),
  CountryAPI(id: 133, name: "Palau", phoneCode: 680),
  CountryAPI(id: 134, name: "Panama", phoneCode: 507),
  CountryAPI(id: 135, name: "Papua New Guinea", phoneCode: 675),
  CountryAPI(id: 136, name: "Paraguay", phoneCode: 595),
  CountryAPI(id: 137, name: "Peru", phoneCode: 51),
  CountryAPI(id: 138, name: "Philippines", phoneCode: 63),
  CountryAPI(id: 139, name: "Poland", phoneCode: 48),
  CountryAPI(id: 140, name: "Portugal", phoneCode: 351),
  CountryAPI(id: 141, name: "Angola", phoneCode: 244),
  CountryAPI(id: 142, name: "Romania", phoneCode: 40),
  CountryAPI(id: 143, name: "Russia", phoneCode: 7),
  CountryAPI(id: 144, name: "Rwanda", phoneCode: 250),
  CountryAPI(id: 145, name: "Saint Kitts and Nevis", phoneCode: 1),
  CountryAPI(id: 146, name: "Saint Lucia", phoneCode: 1),
  CountryAPI(id: 147, name: "Saint Vincent and the Grenadines", phoneCode: 1),
  CountryAPI(id: 148, name: "Samoa", phoneCode: 685),
  CountryAPI(id: 149, name: "San Marino", phoneCode: 378),
  CountryAPI(id: 150, name: "Sao Tome and Principe", phoneCode: 239),
  CountryAPI(id: 151, name: "Algeria", phoneCode: 213),
  CountryAPI(id: 152, name: "Senegal", phoneCode: 221),
  CountryAPI(id: 153, name: "Serbia", phoneCode: 381),
  CountryAPI(id: 154, name: "Seychelles", phoneCode: 248),
  CountryAPI(id: 155, name: "Sierra Leone", phoneCode: 232),
  CountryAPI(id: 156, name: "Singapore", phoneCode: 65),
  CountryAPI(id: 157, name: "Slovakia", phoneCode: 421),
  CountryAPI(id: 158, name: "Slovenia", phoneCode: 386),
  CountryAPI(id: 159, name: "Solomon Islands", phoneCode: 677),
  CountryAPI(id: 160, name: "Somalia", phoneCode: 252),
  CountryAPI(id: 161, name: "South Africa", phoneCode: 27),
  CountryAPI(id: 162, name: "South Sudan", phoneCode: 211),
  CountryAPI(id: 163, name: "Spain", phoneCode: 34),
  CountryAPI(id: 164, name: "Sri Lanka", phoneCode: 94),
  CountryAPI(id: 165, name: "Sudan", phoneCode: 249),
  CountryAPI(id: 166, name: "Suriname", phoneCode: 597),
  CountryAPI(id: 167, name: "Sweden", phoneCode: 46),
  CountryAPI(id: 168, name: "Switzerland", phoneCode: 41),
  CountryAPI(id: 169, name: "Syria", phoneCode: 963),
  CountryAPI(id: 170, name: "Taiwan", phoneCode: 886),
  CountryAPI(id: 171, name: "Tajikistan", phoneCode: 992),
  CountryAPI(id: 172, name: "Tanzania", phoneCode: 255),
  CountryAPI(id: 173, name: "Thailand", phoneCode: 66),
  CountryAPI(id: 174, name: "Timor-Leste", phoneCode: 670),
  CountryAPI(id: 175, name: "Togo", phoneCode: 228),
  CountryAPI(id: 176, name: "Tonga", phoneCode: 676),
  CountryAPI(id: 177, name: "Trinidad and Tobago", phoneCode: 1),
  CountryAPI(id: 178, name: "Tunisia", phoneCode: 216),
  CountryAPI(id: 179, name: "Turkey", phoneCode: 90),
  CountryAPI(id: 180, name: "Turkmenistan", phoneCode: 993),
  CountryAPI(id: 181, name: "Tuvalu", phoneCode: 688),
  CountryAPI(id: 182, name: "Uganda", phoneCode: 256),
  CountryAPI(id: 183, name: "Ukraine", phoneCode: 380),
  CountryAPI(id: 184, name: "Albania", phoneCode: 355),
  CountryAPI(id: 185, name: "United Kingdom", phoneCode: 44),
  CountryAPI(id: 186, name: "United States", phoneCode: 1),
  CountryAPI(id: 187, name: "Uruguay", phoneCode: 598),
  CountryAPI(id: 188, name: "Uzbekistan", phoneCode: 998),
  CountryAPI(id: 189, name: "Vanuatu", phoneCode: 678),
  CountryAPI(id: 190, name: "Vatican City", phoneCode: 379),
  CountryAPI(id: 191, name: "Venezuela", phoneCode: 58),
  CountryAPI(id: 192, name: "Vietnam", phoneCode: 84),
  CountryAPI(id: 193, name: "Yemen", phoneCode: 967),
  CountryAPI(id: 194, name: "Zambia", phoneCode: 260),
  CountryAPI(id: 195, name: "Zimbabwe", phoneCode: 263),
  CountryAPI(id: 197, name: "Weelcomc Sir", phoneCode: 455),
];
